# Generated by Django 5.1.5 on 2025-01-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
