# Generated by Django 5.1.5 on 2025-01-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='title',
        ),
    ]
